# Pseudocode for .github/workflows/tests.yml

# Step 1: Name your workflow
name: "Python Tests"

# Step 2: Define when this workflow should run
on:
  # Which events trigger this workflow?
  # - push to which branches
    push:
      branches: [ main ]
  # - pull requests to main branch
    pull_request:
      branches: [ main ]
  # Allow running this workflow manually from the GitHub UI
    workflow_dispatch:

# Step 3: Define the actual jobs
jobs:
  test:
    # What operating system should this run on?
    runs-on: ubuntu-latest

    # Step 4: Define the sequence of steps
    steps:
      # Step 4.1: Check out the code
      - name: "Checkout repository"
        # Which action to use?
        uses: actions/checkout@v4

      # Step 4.2: Set up Python
      - name: "Set up Python"
        # Which Python setup action?
        uses: actions/setup-python@v4
        # What version to use?
        with:
          python-version: "3.12"

      # Step 4.3: Install dependencies
      - name: "Install dependencies"
        # What commands to run?
        # - pip upgrade?
        # - requirements.txt?
        # - test dependencies?
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      # Step 4.4: Run tests
      - name: "Run tests with pytest"
        # What command to run?
        run: |
          pytest -v --cov=app
        # How to generate coverage?

      # Step 4.5: Upload coverage report
      #- name: "Upload coverage reports"
        # Which coverage action to use?
        # What settings needed?